

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_EXPIRATION} # a day
      refresh-token:
        expiration: 604800000 # 7 days


cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}
  secure: true

twilio:
  account-sid: ${ACCOUNT_SID}
  auth-token: ${AUTH_TOKEN}
  outgoing-sms-number: ${SMS_NUMBER}